# Generated by Django 3.1 on 2020-09-16 00:12

from django.db import migrations
from django.contrib.auth.models import Group, Permission

PERMISSIONS_LIST = [
    'Can add ingredient', 'Can change ingredient', 'Can delete ingredient', 'Can view ingredient',
    'Can add brand', 'Can change brand', 'Can delete brand', 'Can view brand',
    'Can add ingredient serving', 'Can change ingredient serving', 'Can delete ingredient serving', 'Can view ingredient serving',
    'Can add nutritional values', 'Can change nutritional values', 'Can delete nutritional values', 'Can view nutritional values',
    'Can add recipe', 'Can change recipe', 'Can delete recipe', 'Can view recipe',
    'Can add recipe ingredient', 'Can change recipe ingredient', 'Can delete recipe ingredient', 'Can view recipe ingredient',
    'Can add recipe step', 'Can change recipe step', 'Can delete recipe step', 'Can view recipe step',
]

def create_user_group(apps, schema_editor):
    permissions = Permission.objects.filter(name__in=PERMISSIONS_LIST)
    group = Group.objects.create(name='User')
    group.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200914_1559'),
    ]

    operations = [
        migrations.RunPython(create_user_group),
    ]
