# Generated by Django 3.1 on 2020-08-30 05:05

from django.db import migrations

from ..datas import CATEGORIES


def import_ingredient_categories(apps, schema_editor):
    Category = apps.get_model('ingredient', 'IngredientCategory')
    SubCategory = apps.get_model('ingredient', 'IngredientSubCategory')
    for category in CATEGORIES:
        new_category = Category.objects.create(name=category)
        for sub_category in CATEGORIES[category]:
            SubCategory.objects.create(parent_category=new_category, name=sub_category)


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20200830_0441'),
    ]

    operations = [
        migrations.RunPython(import_ingredient_categories),
    ]
