# Generated by Django 3.1 on 2020-08-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_auto_20200830_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredient.ingredientbrand'),
        ),
    ]
