# Generated by Django 3.1 on 2020-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_ingredient_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientserving',
            name='ingredient',
            field=models.ManyToManyField(to='ingredient.Ingredient'),
        ),
    ]
