# Generated by Django 3.1 on 2020-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0012_auto_20200830_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientserving',
            name='custom_name',
            field=models.CharField(blank=True, default='Standard serving', max_length=25),
        ),
    ]
