# Generated by Django 3.1 on 2020-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0013_auto_20200830_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='servings',
            field=models.ManyToManyField(related_name='ingredient', to='ingredient.IngredientServing'),
        ),
    ]
