# Generated by Django 3.1 on 2020-08-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0014_auto_20200830_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='servings',
        ),
        migrations.AddField(
            model_name='ingredientserving',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient'),
        ),
    ]
