# Generated by Django 3.1 on 2020-08-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0015_auto_20200830_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientserving',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='ingredient.ingredient'),
        ),
    ]
