# Generated by Django 3.1 on 2020-08-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0016_auto_20200830_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='nutritional_values',
        ),
    ]
