# Generated by Django 3.1 on 2020-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0017_remove_ingredient_nutritional_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientserving',
            name='grams',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredientserving',
            name='milliliters',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
