# Generated by Django 3.1 on 2020-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0018_auto_20200830_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientserving',
            name='for_list_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
