# Generated by Django 3.1 on 2020-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200830_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.RecipeIngredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='recipe.RecipeStep'),
        ),
    ]
