# Generated by Django 3.1 on 2020-08-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_values', '0006_remove_nutritionalvalues_recipe'),
        ('recipe', '0008_auto_20200830_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutritional_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutritional_values.nutritionalvalues'),
        ),
    ]
