# Generated by Django 3.1 on 2020-09-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipe_nutritional_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_values',
        ),
    ]
