# Generated by Django 3.1 on 2020-09-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20200914_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
