# Generated by Django 3.1 on 2020-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='cholesterol',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='fiber',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='potassium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='saturated_fat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='sodium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='sugars',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='unsaturated_fat',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
