# Generated by Django 3.1 on 2020-08-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0017_remove_ingredient_nutritional_values'),
        ('nutritional_values', '0002_auto_20200830_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalvalues',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_values', to='ingredient.ingredient'),
        ),
    ]
