# Generated by Django 3.1 on 2020-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_values', '0003_nutritionalvalues_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='calories',
            field=models.FloatField(),
        ),
    ]
