# Generated by Django 3.1 on 2020-08-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200830_1922'),
        ('nutritional_values', '0004_auto_20200830_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalvalues',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_values', to='recipe.recipe'),
        ),
    ]
