# Generated by Django 3.1 on 2020-08-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_values', '0005_nutritionalvalues_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalvalues',
            name='recipe',
        ),
    ]
